# This is a basic workflow to help you get started with Actions

name: AIP Notification

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

   # Runs a single command using the runners shell
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta 
      with: 
        node-version: 14.16.1

    # - name: install create-react 
    #   run : npm install -g create-react-app 
    # - name: create basic app  
    #   run:  create-react-app react-basic
    - name: install react and dependencies 
      run:  npm install 
    - name: build the project
      run:  CI="" npm run build
      
   

    - name: Install Surge
      run: npm install --global surge 

    #run: surge ./build hungry-lumber.surge.sh --token ${{secrets.PUSHNOTIFICATION}}
    - name: Run Surge
      run: surge ./build sour-police.surge.sh --token ${{secrets.PUSHNOTIFICATION}}
